theme = "onedark"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[keys.normal]
C-s = ":w" 
space = {"q" = ":qa!", "|" = ":vsplit"}

esc = ["collapse_selection", "keep_primary_selection"]

K = "hover"

"C-h" = "jump_view_left"
"C-j" = "jump_view_down"
"C-k" = "jump_view_up"
"C-l" = "jump_view_right"

# search for word under cursor 
# similar to vim but without the jump (which I prefer anyway)
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection"]


[keys.insert]
C-s = ["normal_mode", ":w"] # save with ctrl s
